# Generated by Django 2.1.4 on 2018-12-30 09:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('rest API', 'REST API'), ('UI', 'UI')], max_length=200)),
                ('trainer', multiselectfield.db.fields.MultiSelectField(choices=[('sai', 'SAI'), ('shiva', 'SHIVA'), ('ganesh', 'GANESH'), ('mahesh', 'MAHESH')], max_length=200)),
                ('timings', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('evening', 'EVENINHG')], max_length=200)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
