# Generated by Django 2.1.4 on 2018-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountClickData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
