# Generated by Django 2.1.4 on 2018-12-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_app', '0002_countclickdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countclickdata',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
